In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy,math


In [2]:
train=pd.read_csv("/workspaces/87071081/machine_learning/multiple_linear_regression/data/house_price_train.csv")
test=pd.read_csv("/workspaces/87071081/machine_learning/multiple_linear_regression/data/house_price_test.csv")


In [3]:
train.head(10)

Unnamed: 0  Id  MSSubClass  MSZoning  LotArea  Street  LotShape  \
0           0   1          60         3     8450       1         3   
1           1   2          20         3     9600       1         3   
2           2   3          60         3    11250       1         0   
3           3   4          70         3     9550       1         0   
4           4   5          60         3    14260       1         0   
5           5   6          50         3    14115       1         0   
6           6   7          20         3    10084       1         3   
7           7   8          60         3    10382       1         0   
8           8   9          50         4     6120       1         3   
9           9  10         190         3     7420       1         3   

   LandContour  Utilities  LotConfig  ...  EnclosedPorch  3SsnPorch  \
0            3          0          4  ...              0          0   
1            3          0          2  ...              0          0   
2            3          0          4  ...              0          0   
3            3          0          0  ...            272          0   
4            3          0          2  ...              0          0   
5            3          0          4  ...              0        320   
6            3          0          4  ...              0          0   
7            3          0          0  ...            228          0   
8            3          0          4  ...            205          0   
9            3          0          0  ...              0          0   

   ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0            0         0        0       2    2008         8              4   
1            0         0        0       5    2007         8              4   
2            0         0        0       9    2008         8              4   
3            0         0        0       2    2006         8              0   
4            0         0        0      12    2008         8              4   
5            0         0      700      10    2009         8              4   
6            0         0        0       8    2007         8              4   
7            0         0      350      11    2009         8              4   
8            0         0        0       4    2008         8              0   
9            0         0        0       1    2008         8              4   

   SalePrice  
0  12.247694  
1  12.109011  
2  12.317167  
3  11.849398  
4  12.429216  
5  11.870600  
6  12.634603  
7  12.206073  
8  11.774520  
9  11.678440  

[10 rows x 72 columns]

Our data set has two unwanted features, (Unnamed and Id) so, we will
remove those. At the end you can see we have a sales price.
sales price is our prediction price, our Y. And all other features are our X.
I have attached a file below which describes our features in detail. Go
have a look on it. house-features
Also the original dataset had a lot of categorical data, which had
character or string in their datafield. Now we cannot train our machine
learning model with categorical (or string) data fields. So I have already
pre-processed the data, converting categorical features into numerical
features.

In [4]:
#Dropping unwanted data from dataset
train = train.drop(["Unnamed: 0", "Id"], axis = 1)
test = test.drop(["Unnamed: 0", "Id"], axis = 1)

In [5]:
#Seperating target and training values
train_data = train.values
Y = train_data[:, -1].reshape(train_data.shape[0], 1)
X = train_data[:, :-1]

test_data = test.values
Y_test = test_data[:, -1].reshape(test_data.shape[0], 1)
X_test = test_data[:, :-1]

In [6]:
print("Shape of X_train :", X.shape)
print("Shape of Y_train :", Y.shape)
print("Shape of X_test :", X_test.shape)
print("Shape of Y_test :", Y_test.shape)

Shape of X_train : (1200, 69)
Shape of Y_train : (1200, 1)
Shape of X_test : (258, 69)
Shape of Y_test : (258, 1)


In [7]:
X_train=np.array(X)
y_train=np.array(Y)

In [8]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (1200, 69), X Type:<class 'numpy.ndarray'>)
[[6.0000e+01 3.0000e+00 8.4500e+03 ... 2.0080e+03 8.0000e+00 4.0000e+00]
 [2.0000e+01 3.0000e+00 9.6000e+03 ... 2.0070e+03 8.0000e+00 4.0000e+00]
 [6.0000e+01 3.0000e+00 1.1250e+04 ... 2.0080e+03 8.0000e+00 4.0000e+00]
 ...
 [2.0000e+01 3.0000e+00 9.1000e+03 ... 2.0090e+03 8.0000e+00 4.0000e+00]
 [2.0000e+01 3.0000e+00 1.1235e+04 ... 2.0060e+03 8.0000e+00 4.0000e+00]
 [2.0000e+01 3.0000e+00 9.3530e+03 ... 2.0060e+03 7.0000e+00 0.0000e+00]]
y Shape: (1200, 1), y Type:<class 'numpy.ndarray'>)
[[12.24769432]
 [12.10901093]
 [12.31716669]
 ...
 [12.08953883]
 [11.90496755]
 [11.66177641]]


In [9]:
values_array = np.random.uniform(0, 100, size=69)

b_init = 785.1811367994083
w_init = np.array(values_array)
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (69,), b_init type: <class 'float'>


In [10]:
def predict_single_loop(x,w,b):
    n=x.shape[0]
    p=0
    for i in range(n):
        p_i=x[i]*w[i]
        p=p+p_i
    p=p+b
    return p

In [11]:
# get a row from our training data
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (69,), x_vec value: [6.000e+01 3.000e+00 8.450e+03 1.000e+00 3.000e+00 3.000e+00 0.000e+00
 4.000e+00 0.000e+00 5.000e+00 2.000e+00 2.000e+00 0.000e+00 5.000e+00
 7.000e+00 5.000e+00 2.003e+03 2.003e+03 1.000e+00 0.000e+00 1.200e+01
 1.300e+01 1.000e+00 1.960e+02 2.000e+00 4.000e+00 2.000e+00 2.000e+00
 3.000e+00 3.000e+00 2.000e+00 7.060e+02 5.000e+00 0.000e+00 1.500e+02
 8.560e+02 1.000e+00 0.000e+00 1.000e+00 4.000e+00 8.540e+02 0.000e+00
 1.710e+03 1.000e+00 0.000e+00 2.000e+00 1.000e+00 3.000e+00 1.000e+00
 2.000e+00 6.000e+00 0.000e+00 1.000e+00 1.000e+00 2.000e+00 4.000e+00
 4.000e+00 2.000e+00 0.000e+00 6.100e+01 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 2.000e+00 2.008e+03 8.000e+00 4.000e+00]
f_wb shape (), prediction: 1268807.4776452782


In [12]:
# get a row from our training data
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (69,), x_vec value: [6.000e+01 3.000e+00 8.450e+03 1.000e+00 3.000e+00 3.000e+00 0.000e+00
 4.000e+00 0.000e+00 5.000e+00 2.000e+00 2.000e+00 0.000e+00 5.000e+00
 7.000e+00 5.000e+00 2.003e+03 2.003e+03 1.000e+00 0.000e+00 1.200e+01
 1.300e+01 1.000e+00 1.960e+02 2.000e+00 4.000e+00 2.000e+00 2.000e+00
 3.000e+00 3.000e+00 2.000e+00 7.060e+02 5.000e+00 0.000e+00 1.500e+02
 8.560e+02 1.000e+00 0.000e+00 1.000e+00 4.000e+00 8.540e+02 0.000e+00
 1.710e+03 1.000e+00 0.000e+00 2.000e+00 1.000e+00 3.000e+00 1.000e+00
 2.000e+00 6.000e+00 0.000e+00 1.000e+00 1.000e+00 2.000e+00 4.000e+00
 4.000e+00 2.000e+00 0.000e+00 6.100e+01 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 2.000e+00 2.008e+03 8.000e+00 4.000e+00]
f_wb shape (), prediction: 1268807.4776452782


In [13]:
def predict(x, w, b):
    """
    single predict using linear regression
    Args:
      x (ndarray): Shape (n,) example with multiple features
      w (ndarray): Shape (n,) model parameters
      b (scalar):             model parameter

    Returns:
      p (scalar):  prediction
    """
    p = np.dot(x, w) + b
    return p

In [14]:
# get a row from our training data
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict(x_vec,w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (69,), x_vec value: [6.000e+01 3.000e+00 8.450e+03 1.000e+00 3.000e+00 3.000e+00 0.000e+00
 4.000e+00 0.000e+00 5.000e+00 2.000e+00 2.000e+00 0.000e+00 5.000e+00
 7.000e+00 5.000e+00 2.003e+03 2.003e+03 1.000e+00 0.000e+00 1.200e+01
 1.300e+01 1.000e+00 1.960e+02 2.000e+00 4.000e+00 2.000e+00 2.000e+00
 3.000e+00 3.000e+00 2.000e+00 7.060e+02 5.000e+00 0.000e+00 1.500e+02
 8.560e+02 1.000e+00 0.000e+00 1.000e+00 4.000e+00 8.540e+02 0.000e+00
 1.710e+03 1.000e+00 0.000e+00 2.000e+00 1.000e+00 3.000e+00 1.000e+00
 2.000e+00 6.000e+00 0.000e+00 1.000e+00 1.000e+00 2.000e+00 4.000e+00
 4.000e+00 2.000e+00 0.000e+00 6.100e+01 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 2.000e+00 2.008e+03 8.000e+00 4.000e+00]
f_wb shape (), prediction: 1268807.4776452787


In [15]:
def compute_cost(X, y, w, b):
    """
    compute cost
    Args:
      X (ndarray (m,n)): Data, m examples with n features
      y (ndarray (m,)) : target values
      w (ndarray (n,)) : model parameters
      b (scalar)       : model parameter

    Returns:
      cost (scalar): cost
    """
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(X[i], w) + b           #(n,)(n,) = scalar (see np.dot)
        cost = cost + (f_wb_i - y[i])**2       #scalar
    cost = cost / (2 * m)                      #scalar
    return cost

In [16]:
# Compute and display cost using our pre-chosen optimal parameters.
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : [1.26698119e+12]


In [17]:
def compute_gradient(X, y, w, b):
    """
    Computes the gradient for linear regression
    Args:
      X (ndarray (m,n)): Data, m examples with n features
      y (ndarray (m,)) : target values
      w (ndarray (n,)) : model parameters
      b (scalar)       : model parameter

    Returns:
      dj_dw (ndarray (n,)): The gradient of the cost w.r.t. the parameters w.
      dj_db (scalar):       The gradient of the cost w.r.t. the parameter b.
    """
    m,n = X.shape           #(number of examples, number of features)
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):
        err = (np.dot(X[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * X[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    return dj_db, dj_dw

In [18]:
#Compute and display gradient
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

/tmp/ipykernel_3020/1291870043.py:21: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dj_dw[j] = dj_dw[j] + err * X[i, j]


dj_db at initial w,b: [1400691.42680684]
dj_dw at initial w,b: 
 [7.60805508e+07 4.21737069e+06 2.27250541e+10 1.38314348e+06
 2.52536388e+06 3.83543347e+06 1.40751205e+03 4.05231556e+06
 1.83149409e+05 1.75256292e+07 2.84885560e+06 2.80955078e+06
 5.17546464e+05 4.22158230e+06 8.69788988e+06 7.79058811e+06
 2.76195913e+09 2.78090970e+09 2.00342838e+06 1.94091865e+05
 1.34922674e+07 1.44303857e+07 2.44135874e+06 1.62856842e+08
 3.52192038e+06 5.23249515e+06 1.95725437e+06 3.12666947e+06
 3.94924453e+06 3.09718669e+06 3.77213241e+06 6.87910972e+08
 6.53939371e+06 7.93722974e+07 7.94589520e+08 1.56187279e+09
 1.45181129e+06 2.16532742e+06 1.32041871e+06 5.19587153e+06
 5.09772053e+08 9.78783838e+06 2.22492155e+09 6.53839550e+05
 9.58301026e+04 2.25527455e+06 5.46423320e+05 4.09058274e+06
 1.46039231e+06 3.22620767e+06 8.03476162e+06 1.00312161e+06
 2.88967637e+06 1.63054985e+06 2.57422874e+06 5.44573756e+06
 5.49531588e+06 2.63111351e+06 1.52116993e+08 6.83682224e+07
 3.02927389e+07 5.43

In [19]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    """
    Performs batch gradient descent to learn theta. Updates theta by taking
    num_iters gradient steps with learning rate alpha

    Args:
      X (ndarray (m,n))   : Data, m examples with n features
      y (ndarray (m,))    : target values
      w_in (ndarray (n,)) : initial model parameters
      b_in (scalar)       : initial model parameter
      cost_function       : function to compute cost
      gradient_function   : function to compute the gradient
      alpha (float)       : Learning rate
      num_iters (int)     : number of iterations to run gradient descent

    Returns:
      w (ndarray (n,)) : Updated values of parameters
      b (scalar)       : Updated value of parameter
      """

    # An array to store cost J and w's at each iteration primarily for graphing later
    J_history = []
    w = copy.deepcopy(w_in)  #avoid modifying global w within function
    b = b_in

    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db,dj_dw = gradient_function(X, y, w, b)   ##None

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               ##None
        b = b - alpha * dj_db               ##None

        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion
            J_history.append( cost_function(X, y, w, b))

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters /10) == 0:
          pass
            #print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")

    return w, b,J_history #return final w,b and J history for graphing

In [21]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient,
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

/tmp/ipykernel_3020/1291870043.py:21: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dj_dw[j] = dj_dw[j] + err * X[i, j]
/tmp/ipykernel_3020/2373855227.py:17: RuntimeWarning: overflow encountered in add
  cost = cost + (f_wb_i - y[i])**2       #scalar
/tmp/ipykernel_3020/2373855227.py:17: RuntimeWarning: overflow encountered in square
  cost = cost + (f_wb_i - y[i])**2       #scalar
/tmp/ipykernel_3020/1291870043.py:21: RuntimeWarning: overflow encountered in add
  dj_dw[j] = dj_dw[j] + err * X[i, j]
/tmp/ipykernel_3020/1291870043.py:21: RuntimeWarning: invalid value encountered in multiply
  dj_dw[j] = dj_dw[j] + err * X[i, j]
/tmp/ipykernel_3020/3045136546.py:32: RuntimeWarning: invalid value encountered in subtract
  w = w - alpha * dj_dw               ##None


In [ ]:
# plot cost versus iteration
fig, (ax1, ax2) = plt.subplots(1, 2, constrained_layout=True, figsize=(12, 4))
ax1.plot(J_hist)
ax2.plot(100 + np.arange(len(J_hist[100:])), J_hist[100:])
ax1.set_title("Cost vs. iteration");  ax2.set_title("Cost vs. iteration (tail)")
ax1.set_ylabel('Cost')             ;  ax2.set_ylabel('Cost')
ax1.set_xlabel('iteration step')   ;  ax2.set_xlabel('iteration step')
plt.show()